SYS:
    caching:
        cacheConfigurations:
            cache_core:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            fluid_template:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_hash:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_pages:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_pagesection:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_phpcode:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_runtime:
                backend: 'TYPO3\CMS\Core\Cache\Backend\TransientMemoryBackend'
            cache_rootline:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            cache_imagesizes:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            l10n:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            extbase_object:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            extbase_reflection:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
            extbase_datamapfactory_datamap:
                backend: 'TYPO3\CMS\Core\Cache\Backend\NullBackend'
