imports:
    - { resource: 'DefaultConfiguration', type: typo3, exclude: [LOG] }
    - { resource: 'includes/*.yaml', type: glob }
    - { resource: '../packages/*/Configuration/Distribution/*.yaml', type: glob, optional: true }

BE:
    explicitADmode: 'explicitAllow'
    loginSecurityLevel: 'normal'
DB:
    Connections:
        Default:
            charset: 'utf8'
FE:
    loginSecurityLevel: 'normal'
GFX:
    jpg_quality: '80'
    processor: 'GraphicsMagick'
    processor_effects: -1
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log'
    TYPO3:
        CMS:
            deprecations:
                writerConfiguration:
                    '%const(TYPO3\CMS\Core\Log\LogLevel::EMERGENCY)%':
                        TYPO3\CMS\Core\Log\Writer\NullWriter: [ ]
            Extbase:
                SignalSlot:
                    Dispatcher:
                        writerConfiguration:
                            '%const(TYPO3\CMS\Core\Log\LogLevel::EMERGENCY)%':
                                TYPO3\CMS\Core\Log\Writer\NullWriter: [ ]
SYS:
    displayErrors: 0
    errorHandlerErrors: 32514
    exceptionalErrors: 4352
    Objects:
        TYPO3\CMS\Core\Configuration\SiteConfiguration:
            className: Helhum\TYPO3\ConfigHandling\Typo3SiteConfiguration
    systemLogLevel: 2
