EXT:
    extConf:
        backend:
            backendFavicon: ''
            backendLogo: ''
            loginBackgroundImage: ''
            loginHighlightColor: ''
            loginLogo: ''
        extensionmanager:
            automaticInstallation: '1'
            offlineMode: '0'
        rsaauth:
            temporaryDirectory: ''
        saltedpasswords:
            BE:
                forceSalted: 0
                onlyAuthService: 0
                saltedPWHashingMethod: 'TYPO3\CMS\Saltedpasswords\Salt\Pbkdf2Salt'
                updatePasswd: 1
            FE:
                enabled: 1
                forceSalted: 0
                onlyAuthService: 0
                saltedPWHashingMethod: 'TYPO3\CMS\Saltedpasswords\Salt\Pbkdf2Salt'
                updatePasswd: 1
        scheduler:
            enableBELog: '1'
            maxLifetime: '1440'
            showSampleTasks: '1'
            useAtdaemon: '0'
