imports:
    - { resource: 'DefaultConfiguration', type: typo3, exclude: [LOG] }
    - { resource: 'includes/*.yaml', type: glob }
    - { resource: '../packages/*/Configuration/Distribution/*.yaml', type: glob, ignore_errors: true }
    # Add or override configuration on deploy targets
    - { resource: 'local.settings.yaml' }

# Reasonable error handling by default
BE:
    explicitADmode: 'explicitAllow'
    loginSecurityLevel: 'normal'
DB:
    Connections:
        Default:
            charset: 'utf8'
FE:
    loginSecurityLevel: 'normal'
GFX:
    jpg_quality: '80'
    processor: 'GraphicsMagick'
    processor_effects: -1
LOG:
    writerConfiguration:
        '%const(TYPO3\CMS\Core\Log\LogLevel::WARNING)%':
            TYPO3\CMS\Core\Log\Writer\FileWriter:
                logFile: '%env(TYPO3_PATH_COMPOSER_ROOT)%/var/log/typo3-warning.log'
SYS:
    displayErrors: 0
    errorHandlerErrors: 32514
    exceptionalErrors: 4352
    systemLogLevel: 2
