version: '3.6'

services:
    web:
        environment:
            - TZ=Europe/Berlin
            - PHP_IDE_CONFIG=serverName=awesome-typo3.test
            - TYPO3_INSTALL_DB_USER=db
            - TYPO3_INSTALL_DB_PASSWORD=db
            - TYPO3_INSTALL_DB_HOST=db
            - TYPO3_INSTALL_DB_PORT=3306
            - TYPO3_INSTALL_DB_UNIX_SOCKET=
            - TYPO3_INSTALL_DB_USE_EXISTING=1
            - TYPO3_INSTALL_DB_DRIVER=mysqli
            - TYPO3_INSTALL_DB_DBNAME=db
            - TYPO3_INSTALL_ADMIN_USER=admin
            - TYPO3_INSTALL_ADMIN_PASSWORD=password
            - TYPO3_INSTALL_SITE_NAME=$DDEV_SITENAME (on DDEV)
            - TYPO3_INSTALL_SITE_SETUP_TYPE=site
            - TYPO3_INSTALL_WEB_SERVER_CONFIG=apache
            - TYPO3_INSTALL_SITE_BASE_URL=https://awesome-typo3.test/
            - TYPO3_INSTALL_OVERRIDE_SETTINGS_FILE=install.override.settings.yaml
    db:
        environment:
            - TZ=Europe/Berlin
